x-logging-common: &logging-common
  logging:
    options:
      max-size: "10m"
      max-file: "3"
services:
  payment_api_mkk:
    container_name: payment_api_mkk
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: payment_app_mkk
    command: [ "bash", "-c", "alembic upgrade heads && python manager.py run-api" ]
    volumes:
      - .:/app
    depends_on:
      - database_mkk
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always

  database_mkk:
    image: postgres:15
    container_name: database_mkk
    volumes:
      - payment_service_db:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${EXTERNAL_DB_PORT:-5432}:5432"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    !!merge <<: *logging-common

  consumer_mkk:
    container_name: consumer_mkk
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: payment_app_mkk
    command: [ "bash", "-c", "python manager.py run-consumer" ]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      rabbitmq_mkk:
        condition: service_healthy
    ports:
      - 8090:8090
    restart: always
    !!merge <<: *logging-common

  rabbitmq_mkk:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq_mkk
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - payment_rabbit_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always

  worker_mkk:
    container_name: worker_mkk
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: payment_app_mkk
    command: [
      "bash",
      "-c",
      "taskiq worker src.worker.main:broker -fsd -tp **/tasks.py -tp **/*_worker.py -tp **/worker.py --workers 1"
    ]
    volumes:
      - .:/app
    expose:
      - 9101
    depends_on:
      - database_mkk
      - rabbitmq_mkk
    env_file:
      - .env
    !!merge <<: *logging-common

  scheduler_mkk:
    container_name: scheduler_mkk
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: payment_app_mkk
    command: [
      "bash",
      "-c",
      "taskiq scheduler src.worker.main:scheduler -fsd -tp **/*_worker.py -tp **/worker.py"
    ]
    volumes:
      - .:/app
    expose:
      - 9102
    depends_on:
      rabbitmq_mkk:
        condition: service_healthy
    !!merge <<: *logging-common


volumes:
  payment_service_db:
  payment_rabbit_data:


networks:
  default:
    name: payment_service_network
